apiVersion: apps/v1
kind: Deployment

metadata:
  name: zero-downtime-green

spec:
  replicas: 2

  selector:
    matchLabels:
      app: zero-downtime-api
      color: green

  template:
    metadata:
      labels:
        app: zero-downtime-api
        color: green

    spec:
      containers:
      - name: zero-downtime-api
        image: zero-downtime-api:v6

        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10